#!/bin/bash

# scripts/compound/auto-compound.sh
# Full pipeline: report → PRD → tasks → implementation → PR

set -e

PROJECT_DIR="/Users/grantcharge/Pickleball-Passport"
cd "$PROJECT_DIR"

echo "$(date): Starting auto-compound..." >> logs/auto-compound.log

# Source environment if exists
if [ -f .env.local ]; then
    source .env.local
fi

# Fetch latest (including tonight's CLAUDE.md updates)
git fetch origin main
git checkout main
git reset --hard origin/main

# Find the latest prioritized report
LATEST_REPORT=$(ls -t reports/*.md 2>/dev/null | head -1)

if [ -z "$LATEST_REPORT" ]; then
    echo "$(date): No reports found in reports/. Skipping auto-compound." >> logs/auto-compound.log
    exit 0
fi

echo "$(date): Using report: $LATEST_REPORT" >> logs/auto-compound.log

# Analyze and pick #1 priority
ANALYSIS=$(./scripts/compound/analyze-report.sh "$LATEST_REPORT")
PRIORITY_ITEM=$(echo "$ANALYSIS" | jq -r '.priority_item // empty')
BRANCH_NAME=$(echo "$ANALYSIS" | jq -r '.branch_name // empty')

if [ -z "$PRIORITY_ITEM" ] || [ -z "$BRANCH_NAME" ]; then
    echo "$(date): Failed to extract priority from report. Analysis: $ANALYSIS" >> logs/auto-compound.log
    exit 1
fi

echo "$(date): Priority item: $PRIORITY_ITEM" >> logs/auto-compound.log
echo "$(date): Branch: $BRANCH_NAME" >> logs/auto-compound.log

# Create feature branch
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

# Create PRD using Claude
echo "$(date): Creating PRD..." >> logs/auto-compound.log
claude -p "Create a detailed PRD (Product Requirements Document) for: $PRIORITY_ITEM. Include user stories, acceptance criteria, technical approach, and edge cases. Save to tasks/prd-$(basename $BRANCH_NAME).md" --dangerously-skip-permissions

# Convert PRD to task list
echo "$(date): Converting PRD to tasks..." >> logs/auto-compound.log
claude -p "Read the PRD at tasks/prd-$(basename $BRANCH_NAME).md. Convert it into an executable task list with atomic tasks. Save as JSON to scripts/compound/prd.json with this structure:
{
  \"feature\": \"$PRIORITY_ITEM\",
  \"tasks\": [
    {\"id\": 1, \"description\": \"...\", \"status\": \"pending\"},
    ...
  ]
}" --dangerously-skip-permissions

# Run the execution loop
echo "$(date): Starting execution loop..." >> logs/auto-compound.log
./scripts/compound/loop.sh 25

# Create PR
echo "$(date): Creating PR..." >> logs/auto-compound.log
git push -u origin "$BRANCH_NAME"
gh pr create --draft --title "Compound: $PRIORITY_ITEM" --body "Auto-generated by nightly compound loop.

## Priority Item
$PRIORITY_ITEM

## Analysis
\`\`\`json
$ANALYSIS
\`\`\`

## Source Report
$LATEST_REPORT
" --base main

echo "$(date): Auto-compound complete!" >> logs/auto-compound.log
